// Auto-generated by scripts/compile-languages.ts

// Basic languages

import './basic-languages-out/shaderlab/manifest.js';
import './basic-languages-out/latex/manifest.js';
import './basic-languages-out/css/manifest.js';
import './basic-languages-out/vb/manifest.js';
import './basic-languages-out/javascript/manifest.js';
import './basic-languages-out/extension-editing/manifest.js';
import './basic-languages-out/coffeescript/manifest.js';
import './basic-languages-out/dotenv/manifest.js';
import './basic-languages-out/julia/manifest.js';
import './basic-languages-out/restructuredtext/manifest.js';
import './basic-languages-out/npm/manifest.js';
import './basic-languages-out/php/manifest.js';
import './basic-languages-out/diff/manifest.js';
import './basic-languages-out/go/manifest.js';
import './basic-languages-out/bat/manifest.js';
import './basic-languages-out/razor/manifest.js';
import './basic-languages-out/scss/manifest.js';
import './basic-languages-out/hlsl/manifest.js';
import './basic-languages-out/java/manifest.js';
import './basic-languages-out/r/manifest.js';
import './basic-languages-out/html/manifest.js';
import './basic-languages-out/python/manifest.js';
import './basic-languages-out/shellscript/manifest.js';
import './basic-languages-out/ini/manifest.js';
import './basic-languages-out/perl/manifest.js';
import './basic-languages-out/objective-c/manifest.js';
import './basic-languages-out/swift/manifest.js';
import './basic-languages-out/powershell/manifest.js';
import './basic-languages-out/groovy/manifest.js';
import './basic-languages-out/xml/manifest.js';
import './basic-languages-out/less/manifest.js';
import './basic-languages-out/fsharp/manifest.js';
import './basic-languages-out/clojure/manifest.js';
import './basic-languages-out/yaml/manifest.js';
import './basic-languages-out/prompt-basics/manifest.js';
import './basic-languages-out/pug/manifest.js';
import './basic-languages-out/search-result/manifest.js';
import './basic-languages-out/markdown-math/manifest.js';
import './basic-languages-out/lua/manifest.js';
import './basic-languages-out/handlebars/manifest.js';
import './basic-languages-out/ruby/manifest.js';
import './basic-languages-out/csharp/manifest.js';
import './basic-languages-out/sql/manifest.js';
import './basic-languages-out/markdown-basics/manifest.js';
import './basic-languages-out/git-base/manifest.js';
import './basic-languages-out/rust/manifest.js';
import './basic-languages-out/make/manifest.js';
import './basic-languages-out/dart/manifest.js';
import './basic-languages-out/cpp/manifest.js';
import './basic-languages-out/configuration-editing/manifest.js';
import './basic-languages-out/json/manifest.js';
import './basic-languages-out/typescript-basics/manifest.js';
import './basic-languages-out/docker/manifest.js';
import './basic-languages-out/log/manifest.js';

// Language features

// Rich language features

import './language-features/typescript/monaco.contribution';
import './language-features/html/monaco.contribution';
import './language-features/css/monaco.contribution';
import './language-features/json/monaco.contribution';